[package]
name = "vortex-cuda"
authors.workspace = true
description = "CUDA compute for Vortex"
edition = { workspace = true }
homepage = { workspace = true }
categories = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lints]
workspace = true

[features]
default = []
_test-harness = []
unstable_encodings = ["vortex/unstable_encodings"]

[dependencies]
arc-swap = { workspace = true }
arrow-schema = { workspace = true, features = ["ffi"] }
async-trait = { workspace = true }
cudarc = { workspace = true, features = ["f16"] }
futures = { workspace = true, features = ["executor"] }
itertools = { workspace = true }
kanal = { workspace = true }
num-traits = { workspace = true }
object_store = { workspace = true, features = ["fs"] }
parking_lot = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true, features = ["std", "attributes"] }
vortex = { workspace = true, features = ["zstd"] }
vortex-array = { workspace = true, features = ["cudarc"] }
vortex-arrow = { workspace = true }
vortex-cub = { path = "cub" }
vortex-cuda-macros = { workspace = true }
vortex-error = { workspace = true, features = ["object_store"] }
vortex-nvcomp = { path = "nvcomp" }
vortex-onpair = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
futures = { workspace = true, features = ["executor"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
vortex-array = { workspace = true, features = ["_test-harness"] }
vortex-cuda = { path = ".", features = ["_test-harness"] }
vortex-fsst = { workspace = true, features = ["_test-harness"] }

[build-dependencies]
bindgen = { workspace = true }
fastlanes = { workspace = true }

[[bench]]
name = "for_cuda"
harness = false

[[bench]]
name = "delta_cuda"
harness = false

[[bench]]
name = "dict_cuda"
harness = false

[[bench]]
name = "zstd_cuda"
harness = false

[[bench]]
name = "filter_cuda"
harness = false

[[bench]]
name = "runend_cuda"
harness = false

[[bench]]
name = "date_time_parts_cuda"
harness = false

[[bench]]
name = "bitpacked_cuda"
harness = false

[[bench]]
name = "alp_cuda"
harness = false

[[bench]]
name = "dynamic_dispatch_cuda"
harness = false

[[bench]]
name = "throughput_cuda"
harness = false

[[bench]]
name = "core_primitives"
harness = false

[[bench]]
name = "fsst_cuda"
harness = false

[[bench]]
name = "onpair_cuda"
harness = false

[[bench]]
name = "list_view_cuda"
harness = false

[[bench]]
name = "arrow_validity_cuda"
harness = false

[[bench]]
name = "arrow_binary_cuda"
harness = false
