[package]
name = "vortex-file"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex file readers and writers"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true, features = ["std", "async-await"] }
itertools = { workspace = true }
kanal = { workspace = true }
moka = { workspace = true, features = ["sync"] }
object_store = { workspace = true, optional = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
tokio = { workspace = true, features = ["rt"], optional = true }
tracing = { workspace = true }
url = { workspace = true }
vortex-alp = { workspace = true }
vortex-array = { workspace = true }
vortex-btrblocks = { workspace = true }
vortex-buffer = { workspace = true }
vortex-bytebool = { workspace = true }

vortex-datetime-parts = { workspace = true }
vortex-decimal-byte-parts = { workspace = true }
vortex-edition = { workspace = true }
vortex-error = { workspace = true }
vortex-fastlanes = { workspace = true }
vortex-flatbuffers = { workspace = true, features = ["file"] }
vortex-fsst = { workspace = true }
vortex-io = { workspace = true }
vortex-layout = { workspace = true }
vortex-mask = { workspace = true }
vortex-metrics = { workspace = true }
vortex-onpair = { workspace = true }
vortex-pco = { workspace = true }
vortex-runend = { workspace = true }
vortex-scan = { workspace = true }
vortex-sequence = { workspace = true }
vortex-session = { workspace = true }
vortex-sparse = { workspace = true }
vortex-tensor = { workspace = true, optional = true }
vortex-utils = { workspace = true, features = ["dashmap"] }
vortex-zigzag = { workspace = true }
vortex-zstd = { workspace = true, optional = true }

[dev-dependencies]
allocator-api2 = { workspace = true }
divan = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vortex-array = { workspace = true, features = ["_test-harness"] }
vortex-io = { workspace = true, features = ["tokio"] }
vortex-layout = { workspace = true, features = ["_test-harness"] }
vortex-scan = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "split_collection"
harness = false

[features]
default = ["wasm-bindgen"]
object_store = ["dep:object_store", "vortex-io/object_store", "tokio"]
tokio = [
    "dep:tokio",
    "vortex-error/tokio",
    "vortex-io/tokio",
    "vortex-layout/tokio",
]
wasm-bindgen = ["vortex-layout/wasm-bindgen"]
zstd = ["dep:vortex-zstd", "vortex-btrblocks/zstd", "vortex-btrblocks/pco"]
# This feature enables unstable encodings for which we don't guarantee stability.
unstable_encodings = [
    "dep:vortex-tensor",
    "vortex-zstd?/unstable_encodings",
    "vortex-btrblocks/unstable_encodings",
]
