[package]
name = "vortex-fastlanes"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex fastlanes arrays"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
fastlanes = { workspace = true }
itertools = { workspace = true }
lending-iterator = { workspace = true }
num-traits = { workspace = true }
prost = { workspace = true }
rand = { workspace = true, optional = true }
seq-macro = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-error = { workspace = true }
vortex-mask = { workspace = true }
vortex-session = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
vortex-alp = { path = "../alp" }
vortex-array = { workspace = true, features = ["_test-harness"] }
vortex-fastlanes = { path = ".", features = ["_test-harness"] }

[features]
_test-harness = ["dep:rand"]

[[bench]]
name = "bitpacking_take"
harness = false

[[bench]]
name = "canonicalize_bench"
harness = false
required-features = ["_test-harness"]

[[bench]]
name = "compute_between"
harness = false
required-features = ["_test-harness"]

[[bench]]
name = "bitpack_compare"
harness = false

[[bench]]
name = "bitpack_compare_sweep"
harness = false

[[bench]]
name = "cast_bitpacked"
harness = false
required-features = ["_test-harness"]
