name: 'Setup Rust'
description: 'Toolchain setup and Initial compilation'
runs:
  using: "composite"
  steps:
    - name: Rust Version
      id: rust-version
      shell: bash
      run: echo "version=$(cat rust-toolchain.toml | grep channel | awk -F'\"' '{print $2}')" >> $GITHUB_OUTPUT

    - name: Rust Toolchain
      id: rust-toolchain
      uses: dtolnay/rust-toolchain@master
      if: steps.rustup-cache.outputs.cache-hit != 'true'
      with:
        toolchain: "${{ steps.rust-version.outputs.version }}"
        components: clippy, rustfmt

    - name: Rust Dependency Cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/develop' }}
        shared-key: "shared" # To allow reuse across jobs
        cache-targets: false

    - name: Cargo clean
      shell: bash
      run: |
        cargo clean

    - name: Rust Compile Cache
      uses: mozilla-actions/sccache-action@v0.0.5
    - name: Rust Compile Cache Config
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV

    - name: Download flatc
      shell: bash
      run: |
        curl -sL https://github.com/google/flatbuffers/releases/download/v24.3.25/Linux.flatc.binary.clang++-15.zip > ${{ runner.temp }}/flatc.zip
        unzip ${{ runner.temp }}/flatc.zip -d ${{ runner.temp }}/flatc
        echo "PATH=${{ runner.temp }}/flatc:$PATH" >> $GITHUB_ENV

    - name: Export Path
      shell: bash
      run: echo "PATH=$PATH" >> $GITHUB_ENV
