allow-expect-in-tests = true
allow-unwrap-in-tests = true
allowed-duplicate-crates = [
    "bitflags",
    "rustls-native-certs",
    "syn",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
