condense_wildcard_suffixes = true
format_macro_matchers = true
format_macro_bodies = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
imports_granularity = "Module"
