[package]
name = "vortex-json"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex JSON extension type"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
arrow-array = { workspace = true }
arrow-schema = { workspace = true, features = ["canonical_extension_types"] }
prost = { workspace = true }
vortex-array = { workspace = true, default-features = false }
vortex-arrow = { workspace = true }
vortex-edition = { workspace = true }
vortex-error = { workspace = true, default-features = false }
vortex-proto = { workspace = true, features = ["expr"] }
vortex-session = { workspace = true }

[dev-dependencies]
vortex-array = { workspace = true, default-features = false, features = [
    "_test-harness",
] }
