[package]
name = "vortex-edition"
authors.workspace = true
description = "Definitions of Vortex editions: named, frozen sets of serialized components with a read-compatibility guarantee"
edition = { workspace = true }
homepage = { workspace = true }
categories = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
parking_lot = { workspace = true }
vortex-session = { workspace = true }
