[package]
name = "xtask"
# This is an internal crate for project developers
authors = { workspace = true }
categories = { workspace = true }
description = "Tasks for repo management"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
publish = false
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "xtask"
test = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
git2 = { workspace = true }
prost-build = { workspace = true }
toml = { workspace = true }
vortex-edition = { workspace = true }
vortex-json = { workspace = true }
vortex-spatial = { workspace = true }
vortex-tensor = { workspace = true }
vortex-zstd = { workspace = true }
xshell = { workspace = true }

[lints]
workspace = true
