[package]
name = "lance-bench"
description = "Lance benchmark tool"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
lance = { version = "10", default-features = false }
lance-encoding = { version = "10" }

anyhow = { workspace = true }
arrow-cast = { version = "58" }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
futures = { workspace = true }
glob = { workspace = true }
parquet = { version = "58" }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
vortex-bench = { workspace = true }

[lib]
test = false

[[bin]]
name = "lance-bench"
test = false

[lints]
workspace = true
