[package]
name = "vortex-tensor"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex tensor extension type"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
vortex-array = { workspace = true, features = ["unstable_row_fns"] }
vortex-arrow = { workspace = true }
vortex-buffer = { workspace = true }
vortex-compressor = { workspace = true }
vortex-edition = { workspace = true }
vortex-error = { workspace = true }
vortex-session = { workspace = true }

arrow-array = { workspace = true }
arrow-schema = { workspace = true }
half = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
prost = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
mimalloc = { workspace = true }
rstest = { workspace = true }
vortex-array = { workspace = true, features = ["_test-harness"] }
vortex-btrblocks = { workspace = true }
vortex-mask = { workspace = true }

[[bench]]
name = "cosine_similarity"
harness = false

[[bench]]
name = "l2_norm"
harness = false

[[bench]]
name = "inner_product"
harness = false
