# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright the Vortex contributors

"""Golden-vector pin for the `measurement_id` hash in `scripts/_measurement_id.py`.

The `measurement_id` computed by `scripts/post-ingest.py --postgres` is the primary key of every
fact row in the benchmarks-website RDS Postgres. Re-ingesting an existing `(commit, dim-tuple)`
upserts via `ON CONFLICT (measurement_id)`; if the hash ever drifted, re-ingests would insert
duplicate rows next to millions of existing ones instead. The hash is therefore frozen forever.

`scripts/measurement_id_golden.json` pins it: the vectors were generated by the original Rust
implementation (`server/src/db.rs` in the now-deleted `vortex-data/benchmarks-website` `server/`
crate, the source of truth at the time the production rows were written). With the Rust side
retired, the golden file is a frozen artifact -- it must NEVER be regenerated, because the ids it
pins are the ids already stored in production. This test asserts the Python port reproduces every
vector byte-for-byte.

Run with:

    uv run --no-project --with pytest --with xxhash pytest scripts/tests/test_measurement_id.py
"""

import importlib.util
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MODULE_PATH = REPO_ROOT / "scripts" / "_measurement_id.py"
GOLDEN_PATH = REPO_ROOT / "scripts" / "measurement_id_golden.json"


def load_measurement_id_module():
    spec = importlib.util.spec_from_file_location("_measurement_id", MODULE_PATH)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_every_golden_vector_reproduces():
    module = load_measurement_id_module()
    golden = json.loads(GOLDEN_PATH.read_text())
    assert golden["seed"] == 0

    for vector in golden["vectors"]:
        port_fn = module.MEASUREMENT_ID_BY_TABLE[vector["table"]]
        computed = port_fn(**vector["fields"])
        assert computed == vector["measurement_id"], (
            f"measurement_id drift for table {vector['table']!r} fields {vector['fields']!r}: "
            f"computed {computed}, golden {vector['measurement_id']}"
        )


def test_every_fact_table_is_covered():
    """Every port function must have at least one golden vector, so a new fact table cannot be
    wired into `MEASUREMENT_ID_BY_TABLE` without also pinning its hash."""
    module = load_measurement_id_module()
    golden = json.loads(GOLDEN_PATH.read_text())

    covered_tables = {vector["table"] for vector in golden["vectors"]}
    assert covered_tables == set(module.MEASUREMENT_ID_BY_TABLE)


def test_random_access_open_mode_preserves_cached_ids_and_separates_reopen():
    module = load_measurement_id_module()
    dimensions = {
        "commit_sha": "0123456789abcdef0123456789abcdef01234567",
        "dataset": "taxi",
        "format": "parquet",
    }

    historical = module.measurement_id_random_access(**dimensions)
    cached = module.measurement_id_random_access(**dimensions, open_mode="cached")
    reopen = module.measurement_id_random_access(**dimensions, open_mode="reopen")

    assert cached == historical
    assert reopen != cached
