[package]
name = "vortex-jni"
description = "Java Native Interface bindings for Vortex"
readme = "README.md"
# This crate is not meant to be consumed by other Rust code but rather produces a static binary
# that can be linked to by other languages.
publish = false
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }

[dependencies]
arrow-array = { workspace = true, features = ["ffi"] }
arrow-data = { workspace = true }
arrow-schema = { workspace = true }
async-fs = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
jni = { workspace = true }
object_store = { workspace = true, features = ["aws", "azure", "gcp"] }
parking_lot = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["std", "log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }
vortex = { workspace = true, features = ["object_store", "files"] }
vortex-arrow = { workspace = true }
vortex-cloud = { workspace = true, features = ["hf", "opendal", "registry"] }
vortex-parquet-variant = { workspace = true }
vortex-spatial = { workspace = true }

[dev-dependencies]
jni = { workspace = true, features = ["invocation"] }
rstest = { workspace = true }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
