[package]
name = "vortex-web-wasm"
version = "0.1.0"
edition = "2024"
rust-version = { workspace = true }
license = "Apache-2.0"
description = "WASM bindings for the Vortex web explorer"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrow-array = { workspace = true }
arrow-ipc = { workspace = true }
arrow-schema = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
vortex = { path = "../../vortex", default-features = false, features = [
    "files",
    "wasm-bindgen",
] }
vortex-arrow = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = { workspace = true }
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = { workspace = true }
console_error_panic_hook = "0.1.7"
js-sys = "0.3.85"
web-sys = { version = "0.3.85", features = [
    "Blob",
    "console",
    "File",
    "FileReader",
] }

[lints]
workspace = true
