[package]
name = "vortex-decimal-byte-parts"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex decimal array (non-canonical) encodings"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
num-traits = { workspace = true }
prost = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-error = { workspace = true }
vortex-mask = { workspace = true }
vortex-session = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
hegeltest = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
vortex-array = { path = "../../vortex-array", features = ["_test-harness"] }
vortex-bench-support = { workspace = true }

[[bench]]
name = "dbp_assemble"
harness = false

[[bench]]
name = "dbp_split"
harness = false
