[package]
name = "vortex-ipc"
authors = { workspace = true }
categories = { workspace = true }
description = "IPC message format to exchange Vortex arrays across processes"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
bytes = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
pin-project-lite = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-error = { workspace = true }
vortex-session = { workspace = true }

[build-dependencies]
vortex-build = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
vortex-array = { workspace = true, features = ["_test-harness"] }

[lints]
workspace = true
