// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Compiles CUB wrapper sources into a shared library and generates Rust bindings.
//!
//! Clients of this crate do not need to configure rpath or other linker settings,
//! as all CUDA dependencies are loaded dynamically at runtime via libloading.

#![expect(clippy::unwrap_used)]
#![expect(clippy::expect_used)]
#![expect(clippy::panic)]

use std::env;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    // Keep CUB's architecture selection in sync with the embedded kernels.
    for name in [
        "CUDA_PATH",
        "PATH",
        "VORTEX_CUDA_ARCH_FLAGS",
        "CUDA_VISIBLE_DEVICES",
        "CUDA_DEVICE_ORDER",
        "NVCC_PREPEND_FLAGS",
        "NVCC_APPEND_FLAGS",
        "NVCC_CCBIN",
    ] {
        println!("cargo:rerun-if-env-changed={name}");
    }
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let kernels_dir = manifest_dir.join("kernels");
    println!("cargo:rerun-if-changed={}", kernels_dir.display());
    generate_rust_bindings(&kernels_dir, &out_dir);

    if !is_cuda_available() {
        return;
    }

    let mut sources = Vec::new();

    for entry in fs::read_dir(&kernels_dir).into_iter().flatten().flatten() {
        let path = entry.path();
        match path.extension().and_then(|e| e.to_str()) {
            Some("cu") => {
                println!("cargo:rerun-if-changed={}", path.display());
                sources.push(path);
            }
            Some("cuh") | Some("h") => {
                println!("cargo:rerun-if-changed={}", path.display());
            }
            _ => {}
        }
    }

    compile_shared_library(&kernels_dir, &sources, &out_dir);
}

fn is_cuda_available() -> bool {
    Command::new("nvcc")
        .arg("--version")
        .output()
        .is_ok_and(|o| o.status.success())
}

fn compile_shared_library(kernel_dir: &Path, sources: &[PathBuf], out_dir: &Path) {
    let lib_path = out_dir.join("libvortex_cub.so");
    let architecture_flags =
        env::var("VORTEX_CUDA_ARCH_FLAGS").unwrap_or_else(|_| "-arch=native".to_owned());
    let mut cmd = Command::new("nvcc");
    cmd.arg("-std=c++20")
        .args(architecture_flags.split_whitespace());

    if env::var("PROFILE").unwrap() == "debug" {
        cmd.args(["-O0", "-g", "-G", "-lineinfo"]);
    } else {
        cmd.arg("-O3");
    }

    cmd.arg("--shared")
        // -fPIC generates position-independent code, which is required for
        // shared libraries as they can be loaded at any memory address.
        .arg("--compiler-options=-fPIC -Wall -Wextra -Werror")
        .arg("--restrict")
        .arg("--include-path")
        .arg(kernel_dir);

    for source in sources {
        cmd.arg(source);
    }

    cmd.arg("-o").arg(&lib_path);

    let output = cmd.output().expect("failed to execute nvcc");
    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "nvcc failed\ncommand: {:?}\nstdout:\n{}\nstderr:\n{}",
            cmd, stdout, stderr
        );
    }
}

fn generate_rust_bindings(kernels_dir: &Path, out_dir: &Path) {
    let header_path = kernels_dir.join("filter.h");

    // Functions are loaded at runtime via libloading to avoid link-time symbol resolution.
    let bindings = bindgen::Builder::default()
        .header(header_path.to_string_lossy())
        .clang_arg(format!("-I{}", kernels_dir.display()))
        // Allow all filter functions
        .allowlist_function("filter_temp_size_.*")
        .allowlist_function("filter_bytemask_.*")
        .allowlist_function("filter_bitmask_.*")
        .allowlist_function("scan_exclusive_sum_.*")
        .allowlist_function("onpair_.*")
        // Allow CUDA types
        .allowlist_type("cudaError_t")
        // Blocklist cudaStream_t and define it manually as an opaque pointer
        .blocklist_type("cudaStream_t")
        .blocklist_type("__int256_t")
        // Generate dynamic library loading wrapper
        .dynamic_library_name("CubLibrary")
        .dynamic_link_require_all(true)
        .wrap_unsafe_ops(true)
        .raw_line("// FFI type definitions for CUB filter operations (generated by bindgen).")
        .raw_line("// Functions are loaded at runtime via libloading.")
        .raw_line("")
        .raw_line("pub type cudaStream_t = *mut std::ffi::c_void;")
        .raw_line("pub type __int256_t = vortex_array::dtype::i256;")
        .generate()
        .expect("Failed to generate CUB bindings");

    bindings.write_to_file(out_dir.join("sys.rs")).unwrap();
}
