name: "Cleanup"
description: "Cleanup workers for more space"
runs:
  using: "composite"
  steps:
    - name: Cleanup workers
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet || true
        sudo rm -rf /opt/ghc || true
        sudo rm -rf "/usr/local/share/boost" || true
        sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
        sudo rm -rf /usr/local/lib/android || true
