// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Export the edition records under `vortex/editions`.
//!
//! Every declared edition gets one TOML file recording what it contains: the identifier, the
//! origin library or project, the minimum origin version whose reader supports it once frozen,
//! and its full member set. Records are grouped by
//! family — `vortex/editions/core/core2025.05.0.toml` — and collected from both the default
//! declarations in `vortex-edition` and optional-component declarations in their owning crates.
//!
//! A draft record carries no compatibility guarantee. Once `min_library_version` is backfilled to
//! document its freeze, the record carries a read-forever guarantee and may never change again.
//! CI enforces that against git history with `cargo run -p xtask -- check-editions`; this exporter
//! enforces the two rules that history cannot see, refusing to delete a record or to unfreeze one.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::anyhow;
use vortex_edition::ComponentKind;
use vortex_edition::EDITION_DECLARATIONS;
use vortex_edition::EDITION_FAMILIES;
use vortex_edition::Edition;
use vortex_edition::EditionDeclaration;
use vortex_edition::EditionFamily;
use vortex_edition::EditionInclusion;
use vortex_edition::EditionSession;

const GENERATED_BY: &str = "# Generated by `cargo run -p xtask -- generate-editions`.\n#";

const FROZEN_NOTE: &str = "\
# This edition is frozen: it carries a read-forever guarantee, so this record of what it
# contains never changes again. Freezing a new edition adds a new file to this directory;
# editing or deleting a frozen one is rejected by CI.";

const DRAFT_NOTE: &str = "\
# This edition record has no read-forever guarantee. It may describe an evolving feature,
# a stable component awaiting adoption, or a release waiting to be cut. New capabilities advance
# to a new edition; after an origin release is known, min_library_version is backfilled to document
# its freeze. A frozen record never changes.";

/// The file recording what a family is, beside that family's editions.
pub const FAMILY_FILE: &str = "family.toml";

/// The edition records, relative to the repository root.
pub const RECORD_DIR: &str = "vortex/editions";

/// Edition families owned by optional Vortex crates rather than the default facade.
static OPTIONAL_EDITION_FAMILIES: &[&EditionFamily] = &[
    &vortex_json::editions::FAMILY,
    &vortex_spatial::editions::FAMILY,
    &vortex_tensor::editions::FAMILY,
    &vortex_zstd::editions::FAMILY,
];

/// Edition declarations owned by optional Vortex crates rather than the default facade.
static OPTIONAL_EDITION_DECLARATIONS: &[&EditionDeclaration] = &[
    &vortex_json::editions::DECLARATION,
    &vortex_spatial::editions::DECLARATION,
    &vortex_tensor::editions::DECLARATION,
    &vortex_zstd::editions::DECLARATION,
];

/// Render a family's record: its name, origin, and what it is for. Unlike an edition record this
/// is documentation, not a contract, so it stays editable.
fn family_record(family: &EditionFamily) -> String {
    let mut lines = vec![
        GENERATED_BY.to_string(),
        "# This describes the family the editions beside it belong to.".to_string(),
        String::new(),
        format!("name = \"{}\"", family.name),
        format!("origin = \"{}\"", family.origin),
        String::new(),
        "doc = \"\"\"".to_string(),
    ];
    lines.extend(wrap(family.doc, 92));
    lines.extend(["\"\"\"".to_string(), String::new()]);
    lines.join("\n")
}

/// Wrap prose to a column, so a long doc reads as a paragraph rather than one endless line.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
}

/// Every component kind and the record key its members are listed under.
const KINDS: [(ComponentKind, &str); 4] = [
    (ComponentKind::Array, "arrays"),
    (ComponentKind::Layout, "layouts"),
    (ComponentKind::DType, "dtypes"),
    (ComponentKind::Aggregate, "aggregates"),
];

/// Render one TOML list per component kind, each sorted by component id.
fn kind_lists(
    lines: &mut Vec<String>,
    inclusions_of: impl Fn(ComponentKind) -> Vec<EditionInclusion>,
) {
    for (kind, key) in KINDS {
        let mut inclusions = inclusions_of(kind);
        inclusions.sort_by_key(|inclusion| inclusion.component_id);
        if inclusions.is_empty() {
            lines.push(format!("{key} = []"));
            continue;
        }
        lines.push(format!("{key} = ["));
        lines.extend(
            inclusions
                .iter()
                .map(|inclusion| format!("    \"{}\",", inclusion.component_id)),
        );
        lines.push("]".to_string());
    }
}

/// Render one edition's record. Deterministic: every list is sorted by component id, so the
/// generated bytes depend only on the declarations.
fn record(session: &EditionSession, edition: &Edition, family: &EditionFamily) -> String {
    let note = if edition.is_draft() {
        DRAFT_NOTE
    } else {
        FROZEN_NOTE
    };
    let mut lines = vec![
        GENERATED_BY.to_string(),
        note.to_string(),
        String::new(),
        format!("edition = \"{}\"", edition.id),
        format!("family = \"{}\"", edition.id.family),
        format!("origin = \"{}\"", family.origin),
    ];
    if let Some(min_library_version) = edition.min_library_version {
        lines.push(format!("min_library_version = \"{min_library_version}\""));
    }
    lines.extend([
        String::new(),
        "# Components added by this edition.".to_string(),
        "[added]".to_string(),
    ]);
    kind_lists(&mut lines, |kind| {
        session
            .components_in(&edition.id, kind)
            .into_iter()
            .filter(|inclusion| inclusion.since == edition.id)
            .collect()
    });
    lines.extend([
        String::new(),
        "# The edition's full membership: the members above, plus every member of earlier"
            .to_string(),
        "# editions of the family.".to_string(),
        "[components]".to_string(),
    ]);
    kind_lists(&mut lines, |kind| session.components_in(&edition.id, kind));
    lines.push(String::new());
    lines.join("\n")
}

/// The records present on disk, as `family/edition.toml` paths relative to the record
/// directory. A record filed under the wrong family reads as a stray, which is what it is.
fn existing_records(dir: &Path) -> anyhow::Result<BTreeSet<String>> {
    let mut records = BTreeSet::new();
    if !dir.exists() {
        return Ok(records);
    }
    for family in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let family = family?.path();
        if !family.is_dir() {
            continue;
        }
        for entry in
            fs::read_dir(&family).with_context(|| format!("reading {}", family.display()))?
        {
            let path = entry?.path();
            if path
                .extension()
                .is_some_and(|extension| extension == "toml")
                && let Ok(relative) = path.strip_prefix(dir)
                && let Some(relative) = relative.to_str()
            {
                records.insert(relative.to_string());
            }
        }
    }
    Ok(records)
}

/// A record carries a `min_library_version` once its freeze has been documented.
fn records_a_frozen_edition(contents: &str) -> bool {
    contents
        .lines()
        .any(|line| line.starts_with("min_library_version = "))
}

pub fn generate_editions() -> anyhow::Result<()> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(RECORD_DIR);
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    let session = EditionSession::empty();
    for family in EDITION_FAMILIES
        .iter()
        .copied()
        .chain(OPTIONAL_EDITION_FAMILIES.iter().copied())
    {
        session
            .declare_family(family)
            .map_err(|error| anyhow!("declaring edition families: {error}"))?;
    }
    for declaration in EDITION_DECLARATIONS
        .iter()
        .copied()
        .chain(OPTIONAL_EDITION_DECLARATIONS.iter().copied())
    {
        session
            .declare(declaration)
            .map_err(|error| anyhow!("declaring editions: {error}"))?;
    }
    session
        .validate()
        .map_err(|error| anyhow!("validating editions: {error}"))?;

    let mut expected = BTreeSet::new();
    for family in session.families() {
        let relative = format!("{}/{FAMILY_FILE}", family.name);
        let path = dir.join(&relative);
        expected.insert(relative);
        fs::create_dir_all(dir.join(family.name))
            .with_context(|| format!("creating the {} record directory", family.name))?;
        fs::write(&path, family_record(&family))
            .with_context(|| format!("writing {}", path.display()))?;
    }

    for edition in session.editions() {
        let relative = format!("{}/{}.toml", edition.id.family, edition.id);
        let path = dir.join(&relative);
        expected.insert(relative);
        fs::create_dir_all(dir.join(edition.id.family))
            .with_context(|| format!("creating the {} record directory", edition.id.family))?;

        // Freezing is permanent, and the record on disk is the only memory of it. Refusing
        // here means unfreezing cannot be laundered through the exporter.
        if edition.is_draft()
            && let Ok(previous) = fs::read_to_string(&path)
            && records_a_frozen_edition(&previous)
        {
            return Err(anyhow!(
                "{} is recorded as frozen but its declaration is now a draft.\n\
                 An edition that recorded a min_library_version carries a read-forever \
                 guarantee and may never return to draft.",
                edition.id,
            ));
        }

        let family = session.find_family(edition.id.family).ok_or_else(|| {
            anyhow!(
                "edition {} belongs to undeclared family {}",
                edition.id,
                edition.id.family
            )
        })?;
        fs::write(&path, record(&session, &edition, &family))
            .with_context(|| format!("writing {}", path.display()))?;
    }

    let strays: Vec<String> = existing_records(&dir)?
        .difference(&expected)
        .cloned()
        .collect();
    if !strays.is_empty() {
        return Err(anyhow!(
            "{} has records with no declared edition behind them: {strays:?}.\n\
             A frozen edition may never be deleted; its declaration must stay in the \
             generator's edition declarations.",
            dir.display(),
        ));
    }

    Ok(())
}
