[package]
name = "duckdb-bench"
description = "DuckDB benchmarks tool"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[package.metadata.cargo-shear]
ignored = ["vortex-cuda"]

[[bin]]
name = "duckdb-bench"
test = false

[lib]
test = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
similar = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
vortex = { workspace = true }
vortex-bench = { workspace = true }
vortex-cuda = { workspace = true, optional = true }
vortex-duckdb = { workspace = true }

[features]
cuda = ["dep:vortex-cuda"]
unstable_encodings = ["vortex/unstable_encodings"]

[lints]
workspace = true
