name: Fuzz

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  fuzz:
    name: 'fuzz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cleanup
      - uses: ./.github/actions/setup-rust
      - name: Install cargo fuzz
        run: cargo install cargo-fuzz
      - uses: actions/cache@v4
        name: Restore corpus
        with:
          path: fuzz/corpus
          key: array_ops-${{ hashFiles('fuzz/corpus/array_ops/*') }}
          restore-keys: |
            array_ops-
      - name: Run fuzzing target
        run: RUST_BACKTRACE=1 cargo fuzz run array_ops -- -max_total_time=1800
        continue-on-error: true
      - name: Archive crash artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-crash-artifacts
          path: fuzz/artifacts
