name: Fuzz

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  fuzz:
    name: 'fuzz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cleanup
      - uses: ./.github/actions/setup-rust
      - name: Install cargo fuzz
        run: cargo install cargo-fuzz
      - name: Restore corpus
        shell: bash
        run: |
          aws s3 cp s3://vortex-fuzz-corpus/array_ops_corpus.tar.zst . --endpoint-url https://01e9655179bbec953276890b183039bc.r2.cloudflarestorage.com
          tar -xf array_ops_corpus.tar.zst
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_FUZZ_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_FUZZ_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
      - name: Run fuzzing target
        run: RUST_BACKTRACE=1 cargo fuzz run array_ops -- -max_total_time=3600
        continue-on-error: true
      - name: Archive crash artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-crash-artifacts
          path: fuzz/artifacts
      - name: Persist corpus
        shell: bash
        run: |
          tar -acf array_ops_corpus.tar.zst fuzz/corpus/array_ops
          aws s3 cp array_ops_corpus.tar.zst s3://vortex-fuzz-corpus --endpoint-url https://01e9655179bbec953276890b183039bc.r2.cloudflarestorage.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_FUZZ_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_FUZZ_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
