name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - develop

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to pull full commit history for release version number inference
          fetch-depth: 0

      - uses: ./.github/actions/cleanup

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: ./.github/actions/setup-rust
      - uses: ./.github/actions/setup-python

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
