name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - develop

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.run-release-plz.outputs.releases_created }}  # Expose this step output as a job output
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to pull full commit history for release version number inference
          fetch-depth: 0

      - uses: ./.github/actions/cleanup

      - uses: ./.github/actions/setup-rust
      - uses: ./.github/actions/setup-python

      - name: Run release-plz
        id: run-release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  release-to-pypi:
    name: Release to PyPI
    needs: release-plz
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    if: ${{ needs.release-plz.outputs.releases_created == "true" }}
    uses: ./.github/workflows/publish-vortex.yml
